---
language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - 1.11
  - 1.12
  - tip
before_script:
  - go get github.com/mattn/goveralls
  - PATH=$PATH:$HOME/gopath/bin goveralls -service=travis-ci -repotoken=$COVERALLS_TOKEN
script:
  - go test
